Update device-tests.yml

diff --git a/.github/workflows/device-tests.yml b/.github/workflows/device-tests.yml
--- a/.github/workflows/device-tests.yml
+++ b/.github/workflows/device-tests.yml
@@ -8,112 +8,119 @@ on:
   pull_request:
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+
+  list-system-images:
+    runs-on: macos-12
     steps:
-      - name: Cancel Previous Runs
-        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # Tag: 0.11.0
+      - run: sdkmanager --list | grep system-images
 
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          submodules: recursive
 
-      - name: Setup Environment
-        uses: ./.github/actions/environment
+  # build:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Cancel Previous Runs
+  #       uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # Tag: 0.11.0
 
-      - name: Build Native Dependencies
-        uses: ./.github/actions/buildnative
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: recursive
 
-      - name: Restore .NET Dependencies
-        run: dotnet restore test/Sentry.Maui.Device.TestApp --nologo
+  #     - name: Setup Environment
+  #       uses: ./.github/actions/environment
 
-      - name: Build Android Test App
-        run: dotnet build test/Sentry.Maui.Device.TestApp -c Release -f net6.0-android --no-restore --nologo
+  #     - name: Build Native Dependencies
+  #       uses: ./.github/actions/buildnative
 
-      - name: Upload Android Test App
-        uses: actions/upload-artifact@v3
-        with:
-          name: device-test-android
-          if-no-files-found: error
-          path: test/Sentry.Maui.Device.TestApp/bin/Release/net6.0-android/io.sentry.dotnet.maui.device.testapp-Signed.apk
+  #     - name: Restore .NET Dependencies
+  #       run: dotnet restore test/Sentry.Maui.Device.TestApp --nologo
 
-  android:
-    needs: [build]
-    name: Run Android API-${{ matrix.api-level }} Test
-    runs-on: macos-12 # MacOS is required for the emulator, per https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md
-    strategy:
-      fail-fast: false
-      matrix:
-        api-level: [27, 28, 29, 30, 31, 32, 33]
-    env:
-      DOTNET_CLI_TELEMETRY_OPTOUT: 1
-      DOTNET_NOLOGO: 1
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  #     - name: Build Android Test App
+  #       run: dotnet build test/Sentry.Maui.Device.TestApp -c Release -f net6.0-android --no-restore --nologo
 
-      - name: Download test app artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: device-test-android
-          path: bin
+  #     - name: Upload Android Test App
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: device-test-android
+  #         if-no-files-found: error
+  #         path: test/Sentry.Maui.Device.TestApp/bin/Release/net6.0-android/io.sentry.dotnet.maui.device.testapp-Signed.apk
 
-      - name: Install xharness
-        run: dotnet tool install Microsoft.DotNet.XHarness.CLI --global --version "1.*-*"
+  # android:
+  #   needs: [build]
+  #   name: Run Android API-${{ matrix.api-level }} Test
+  #   runs-on: macos-12 # MacOS is required for the emulator, per https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       api-level: [27, 28, 29, 30, 31, 32, 33]
+  #   env:
+  #     DOTNET_CLI_TELEMETRY_OPTOUT: 1
+  #     DOTNET_NOLOGO: 1
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      # Cached AVD setup per https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md
-      # Note: The Gradle cache is required for the AVD cache to work correctly.
+  #     - name: Download test app artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: device-test-android
+  #         path: bin
 
-      - name: Gradle cache
-        uses: gradle/gradle-build-action@3fdd6f3efd56a322d1134aa883bcde16d467f02c
+  #     - name: Install xharness
+  #       run: dotnet tool install Microsoft.DotNet.XHarness.CLI --global --version "1.*-*"
 
-      - name: AVD cache
-        uses: actions/cache@v3
-        id: avd-cache
-        with:
-          path: |
-            ~/.android/avd/*
-            ~/.android/adb*
-          key: avd-${{ matrix.api-level }}
+  #     # Cached AVD setup per https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md
+  #     # Note: The Gradle cache is required for the AVD cache to work correctly.
 
-      - name: Create AVD and generate snapshot for caching
-        if: steps.avd-cache.outputs.cache-hit != 'true'
-        timeout-minutes: 30
-        uses: mattjohnsonpint/android-emulator-runner@6660ec2b55b905deb5a36e169ce498e5aceec2a9
-        with:
-          api-level: ${{ matrix.api-level }}
-          target: ${{ matrix.api-level >= 30 && 'aosp_atd' || 'default' }}
-          channel: ${{ matrix.api-level >= 30 && 'canary' || 'stable' }}
-          force-avd-creation: false
-          ram-size: 2048M
-          arch: x86_64
-          disk-size: 4096M
-          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-          script: echo "Generated AVD snapshot for caching."
+  #     - name: Gradle cache
+  #       uses: gradle/gradle-build-action@3fdd6f3efd56a322d1134aa883bcde16d467f02c
 
-      - name: Run Tests
-        timeout-minutes: 30
-        uses: mattjohnsonpint/android-emulator-runner@6660ec2b55b905deb5a36e169ce498e5aceec2a9
-        with:
-          api-level: ${{ matrix.api-level }}
-          target: ${{ matrix.api-level >= 30 && 'aosp_atd' || 'default' }}
-          channel: ${{ matrix.api-level >= 30 && 'canary' || 'stable' }}
-          force-avd-creation: false
-          ram-size: 2048M
-          arch: x86_64
-          disk-size: 4096M
-          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-          script: xharness android test --output-directory=./test_output --app=bin/io.sentry.dotnet.maui.device.testapp-Signed.apk --package-name=io.sentry.dotnet.maui.device.testapp
+  #     - name: AVD cache
+  #       uses: actions/cache@v3
+  #       id: avd-cache
+  #       with:
+  #         path: |
+  #           ~/.android/avd/*
+  #           ~/.android/adb*
+  #         key: avd-${{ matrix.api-level }}
 
-      - name: Create Test Report
-        if: success() || failure()
-        run: scripts/parse-xunit2-xml.ps1 ./test_output/TestResults.xml | Out-File $env:GITHUB_STEP_SUMMARY
-        shell: pwsh
+  #     - name: Create AVD and generate snapshot for caching
+  #       if: steps.avd-cache.outputs.cache-hit != 'true'
+  #       timeout-minutes: 30
+  #       uses: mattjohnsonpint/android-emulator-runner@6660ec2b55b905deb5a36e169ce498e5aceec2a9
+  #       with:
+  #         api-level: ${{ matrix.api-level }}
+  #         target: ${{ matrix.api-level >= 30 && 'aosp_atd' || 'default' }}
+  #         channel: ${{ matrix.api-level >= 30 && 'canary' || 'stable' }}
+  #         force-avd-creation: false
+  #         ram-size: 2048M
+  #         arch: x86_64
+  #         disk-size: 4096M
+  #         emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+  #         script: echo "Generated AVD snapshot for caching."
 
-      - name: Upload results
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: device-test-android-${{ matrix.api-level }}-results
-          path: test_output
+  #     - name: Run Tests
+  #       timeout-minutes: 30
+  #       uses: mattjohnsonpint/android-emulator-runner@6660ec2b55b905deb5a36e169ce498e5aceec2a9
+  #       with:
+  #         api-level: ${{ matrix.api-level }}
+  #         target: ${{ matrix.api-level >= 30 && 'aosp_atd' || 'default' }}
+  #         channel: ${{ matrix.api-level >= 30 && 'canary' || 'stable' }}
+  #         force-avd-creation: false
+  #         ram-size: 2048M
+  #         arch: x86_64
+  #         disk-size: 4096M
+  #         emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+  #         script: xharness android test --output-directory=./test_output --app=bin/io.sentry.dotnet.maui.device.testapp-Signed.apk --package-name=io.sentry.dotnet.maui.device.testapp
+
+  #     - name: Create Test Report
+  #       if: success() || failure()
+  #       run: scripts/parse-xunit2-xml.ps1 ./test_output/TestResults.xml | Out-File $env:GITHUB_STEP_SUMMARY
+  #       shell: pwsh
+
+  #     - name: Upload results
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: device-test-android-${{ matrix.api-level }}-results
+  #         path: test_output
